apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server
spec:
  replicas: 2
  minReadySeconds: 5
  selector:
    matchLabels:
      app: node-server
  template:
    metadata:
      labels:
        app: node-server
    spec:
      containers:
        - image: node-server:1.0
          name: node-server
